name: CI/CD Pipeline

on:
  push:
    branches: [ "master", "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  test:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase repo name
        run: |
          echo "LOWER_REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Run tests with Docker Compose
        run: |
          docker build -f Dockerfile.test -t app-test .
          docker compose -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from test_runner

  build:
    runs-on: self-hosted
    needs: test
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase repo name
        run: |
          echo "LOWER_REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push production image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.LOWER_REPO }}:latest

  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase repo name
        run: |
          echo "LOWER_REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 58529
          envs: GITHUB_TOKEN
          script: |
            podman pull ghcr.io/${{ env.LOWER_REPO }}:latest
            podman stop my-app || true
            podman rm my-app || true
            podman run -d \
              --name my-app \
              --restart always \
              --network host \
              -e DATABASE_URL='postgresql+psycopg://kubsu:kubsu@localhost:5432/kubsu' \
              ghcr.io/${{ env.LOWER_REPO }}:latest
            podman image prune -f
